### ISSUE TITLE
List of issues to be fixed

### ISSUE THREAD

**Issue by rtgdk** [spdx/spdx_python_licensematching#11]
- [x] Move text files in a separate directory. Keep code and text files in separate files 
           

- Text files needed for code should be moved to resouces/ folder. Licenses and templates text files should be moved to data/ folder. Test folder should only have python test files, move the other files to data/ or resources folder.

- [x] Provide help when arguments are not passed or incorrect argument passed - Use argparse 

- [x] Update Readme - include more details about the working of the tool. Include setup instructions for developers and other resources.

- [x] Tool should be able to identify near close matches. (haven't tested this scenario yet myself)

- [x] Tool should be importable by other projects (packaging the project)

- [x] Clear names for folder(modules)

- [x] Users should not be required to cd into the directory to run the files (either remove from readme or provide short paths or provide a quick way to run those - maybe look into how to package a python project )

- [x] Add travis or github actions to run tests on pull requests/commits

- [x] Add more tests (both unit and functional tests)

- [x] Add examples to run/use the code in different ways (like importing) - Mayeb look at https://github.com/spdx/tools-python/

- [x] Fix readme to run all tests together instead of providing separate commands for run tests for template and licenses

- [x] Right now, we are just printing the output of the functions - `The Text and the Template do not Match.`. We should also  provide some kind of exit code and some additionional messages where the mismatch happened. This would be really useful when using the tool in some other project

- [x]  When I run `python3 compare_template_text.py -h`.  It prints `The Text and the Template Match.`, please move the main  code inside a function `def foo(args)`that is called by def main() functions - arguments are parsed inside the main() function and then it calls `foo(args)` - this is a better way to run scripts - https://realpython.com/python-main-function/

**Comment by rtgdk** [comment]
@anshuldutt21  Please use `data/` and `resources` folder to store text files

`data/` for any files that are used by examples/tests

`resources` for any files that is used by the main code.

**Comment by rtgdk** [comment]
@anshuldutt21 I am not sure how you have marked `packaging the project` and `Move text files in a separate directory.` I don't see it done. For packaging the project - please see the python documentation or any other articles - you would have to add __init__.py files atleast . and do other modifications as well. Let's keep these changes in mind for task 4.

**Comment by rtgdk** [comment]
@anshuldutt21 Please keep the duplicate code and files to minimum, I saw `equivalentwords.txt` and `test.txt` in every module, lets move it resouces/ folder. Also please follow python packaging guidelines. Let me know if you can't find a good article on that.

**Comment by anshuldutt21** [comment]
@rtgdk  I am having trouble with implementing the functionality that the user can run the code from any directory. In that I am not sure how to specify the absolute path for the data files. If a User runs it from the main directory then path = os.getcwd() + "data". But if he runs it from other dir, path = os.getcwd() + "../data" is the path I am specifying in the code. This problem is only with the text files as they need a specific path to be opened in the script. eg- equivalentwords.txt, data_templates,etc.

**Comment by anshuldutt21** [comment]
Can we close this issue now @rtgdk

**Comment by rtgdk** [comment]
Yeah
